apiVersion: v1
kind: Deploy
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    ports:
      - container Port:80
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}
